### ISSUE TITLE
When navigating back from the albums view, the artistsViewModel cannot initialize

### ISSUE THREAD

**Issue by janis-kra** [enpit/jet-spotify-explorer#3]
```
ojcore.js:261 TypeError: Cannot read property 'nodeType' of null
    at Object.ko.contextFor (http://localhost:8000/js/libs/knockout/knockout-3.4.0.debug.js:3385:21)
    at Object.ko.dataFor (http://localhost:8000/js/libs/knockout/knockout-3.4.0.debug.js:3396:26)
    at new ArtistViewModel (http://localhost:8000/js/viewModels/artist.js:17:28)
    at http://localhost:8000/js/libs/oj/v2.1.0/debug/ojmodule.js:210:31oj.Logger._write @ ojcore.js:261oj.Logger.error @ ojcore.js:157(anonymous function) @ ojmodule.js:454
document.getElementById('search')
```

**Comment by janis-kra** [comment]
Using postbox fixes this
